### ISSUE TITLE
Fast breeder reactor upkeep

### ISSUE THREAD

**Issue by alsimoneau** [doubleaxe/daxfb-calculator#6]
The Fast Breeder Reactor has an optional enrichment recipe that is done automatically if blankets are provided but doesn't throttle the main reaction.

This is currently modeled by having the enrichment process as a separate recipe. However, the enrichment node still contributes to the population, maintenance and computing requirements.

I don't know the best solution, but potentially creating a different node specifically for the enrichment process would be the simplest solution.

**Comment by doubleaxe** [comment]
Hello.

For backward compatibility I left this enrichment process as separate recipe, because it was like this in previous version. I didn't think about upkeep cost.

I could merge this recipe, so FBR will have either plain fuel-to-steam recipe and fuel-to-steam+enrichment.

Actually enrichment process cannot work without fuel-to-steam, and this will follow in game behavior close enough.

**Comment by alsimoneau** [comment]
The opposite is true though, and in a balanced system the enrichment is
over producing slightly.

**Comment by doubleaxe** [comment]
Made this:
![image](https://github.com/doubleaxe/daxfb-calculator/assets/11171575/fb944b21-d4ae-4a44-80fc-484ff38298b2)

It will be a little quirky if you want parts of this recipe to have different rates, you will have to use storages to supply/remove exceed resources, but it is most I can do without changing many parts of project.

**Comment by doubleaxe** [comment]
Fixed in v1.0.20
